export const catalog = [
  { id: 'chocolate-chip-cookie', name: 'Chocolate Chip Cookie Spinner', family: 'Cookie Counter', type: 'Spin', image: '/assets/chocolate-chip-cookie.webp', makerworld: 'https://makerworld.com/en/models/2944943-chocolate-chip-cookie-fidget-spinner', description: 'A classic cookie look with a smooth spinning center.' },
  { id: 'black-white-cookie', name: 'Black & White Cookie Spinner', family: 'Cookie Counter', type: 'Spin', image: '/assets/black-white-cookie.webp', makerworld: 'https://makerworld.com/en/models/2944564-black-and-white-cookie-fidget-spinner', description: 'A bakery favorite with two sides of fun.' },
  { id: 'peanut-butter-cookie', name: 'Peanut Butter Cookie Fidget', family: 'Cookie Counter', type: 'Fidget', image: '/assets/peanut-butter-cookie.webp', makerworld: 'https://makerworld.com/en/models/2944486-peanut-butter-cookie-fidget', description: 'A sweet little pocket-sized play break.' },
  { id: 'chocolate-cupcake', name: 'Chocolate Cupcake Spinner', family: 'Sweet Treats', type: 'Spin', image: '/assets/chocolate-cupcake.webp', makerworld: 'https://makerworld.com/en/models/2940355-chocolate-cupcake-fidget-spinner-toy', description: 'A cupcake you can spin, with zero crumbs.' },
  { id: 'fortune-cookie', name: 'Fortune Cookie Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/fortune-cookie.webp', makerworld: 'https://makerworld.com/en/models/2832394-cute-fortune-cookie-wiggle-print-in-place-toy', description: 'A tiny desk friend with a lot of personality.' },
  { id: 'lo-mein', name: 'Lo Mein Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/lo-mein.webp', makerworld: 'https://makerworld.com/en/models/2832368-cute-lo-mein-wiggle-print-in-place-desk-toy', description: 'Noodle-inspired joy for fidgety fingers.' },
  { id: 'california-roll', name: 'California Roll Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/california-roll.webp', makerworld: 'https://makerworld.com/en/models/2832307-cute-california-roll-wiggle-print-in-place-toy', description: 'A playful sushi-shaped desk companion.' },
  { id: 'salmon-nigiri', name: 'Salmon Nigiri Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/salmon-nigiri.webp', makerworld: 'https://makerworld.com/en/models/2832222-cute-salmon-nigiri-wiggle-print-in-place-toy', description: 'Small, cheerful, and made to wiggle.' },
  { id: 'soy-sauce', name: 'Soy Sauce Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/soy-sauce.webp', makerworld: 'https://makerworld.com/en/models/2832176-cute-soy-sauce-wiggle-print-in-place-desk-toy', description: 'A little sidekick for the whole sushi crew.' },
  { id: 'egg-roll', name: 'Egg Roll Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/egg-roll.webp', makerworld: 'https://makerworld.com/en/models/2832035-cute-egg-roll-wiggle-print-in-place-desk-toy', description: 'A snack-inspired toy that keeps moving.' },
  { id: 'dumpling', name: 'Dumpling Wiggle', family: 'Little Wiggles', type: 'Wiggle', image: '/assets/dumpling.webp', makerworld: 'https://makerworld.com/en/models/2831942-cute-dumpling-wiggle-print-in-place-desk-toy', description: 'The happiest little dumpling on your desk.' }
];
