export const catalog = [
  { id: 'italian-jelly-cookie', category: 'fidgets', fidgetType: 'slider', name: 'Italian Jelly Cookie', priceCents: 800, image: '/assets/italian-jelly-cookie-photo.jpg', imageKind: 'photo', type: 'Magnet Slider', description: 'A jelly-filled bakery favorite with a magnetic slide.', detail: 'Inspired by an Italian jelly cookie, with a playful magnetic sliding motion and a colorful layered look.' },
  { id: 'peanut-butter-sandwich-cookie', category: 'fidgets', fidgetType: 'slider', name: 'Peanut Butter Sandwich Cookie', priceCents: 800, image: '/assets/peanut-butter-sandwich-cookie-photo.jpg', imageKind: 'photo', type: 'Magnet Slider', description: 'A peanut-shaped sandwich cookie made to slide.', detail: 'The crisscross cookie texture and layered sandwich shape make this magnetic slider a sweet little hand-held toy.' },
  { id: 'elf-fudge-cookie', category: 'fidgets', fidgetType: 'slider', name: 'Elf Fudge Cookie', priceCents: 800, image: '/assets/photo-coming-soon.svg', imageKind: 'pending', type: 'Magnet Slider', description: 'A fudge-cookie-inspired magnetic slider.', detail: 'An Elf Fudge Cookie design with a magnetic sliding motion. A real product photo is coming soon.' },
  { id: 'rainbow-cookie', category: 'fidgets', fidgetType: 'slider', name: 'Rainbow Cookie', priceCents: 800, image: '/assets/rainbow-cookie-photo.jpg', imageKind: 'photo', type: 'Magnet Slider', description: 'Colorful cookie layers with a magnetic slide.', detail: 'A layered rainbow-cookie design with a magnetic sliding motion and a chocolate-brown top.' },
  { id: 'black-white-sandwich-cookie', category: 'fidgets', fidgetType: 'slider', name: 'Black and White Sandwich Cookie', priceCents: 800, image: '/assets/photo-coming-soon.svg', imageKind: 'pending', type: 'Magnet Slider', description: 'A two-tone sandwich cookie with a magnetic slide.', detail: 'A black-and-white sandwich-cookie design with a magnetic sliding motion. A real product photo is coming soon.' },
  { id: 'chocolate-cupcake', category: 'fidgets', fidgetType: 'spinner', name: 'Chocolate Cupcake', priceCents: 800, image: '/assets/chocolate-cupcake-photo.jpg', imageKind: 'photo', type: 'Spinner', description: 'A cupcake-shaped fidget that spins.', detail: 'A chocolate cupcake-inspired 3D printed spinner with a dark base and a swirl-topped look.' },
  { id: 'chocolate-chip-cookie', category: 'fidgets', fidgetType: 'spinner', name: 'Chocolate Chip Cookie', priceCents: 800, image: '/assets/chocolate-chip-cookie-photo.jpg', imageKind: 'photo', type: 'Spinner', description: 'The classic chocolate chip cookie, ready to spin.', detail: 'A chocolate-chip-cookie-inspired 3D printed spinner with raised chocolate chips and a warm cookie color.' },
  { id: 'black-white-half-moon-cookie', category: 'fidgets', fidgetType: 'spinner', name: 'Black and White Half Moon Cookie', priceCents: 800, image: '/assets/black-white-half-moon-cookie-photo.jpg', imageKind: 'photo', type: 'Spinner', description: 'A half-black, half-white cookie that spins.', detail: 'A half-moon cookie-inspired 3D printed spinner with a clean black-and-white top.' },
  { id: 'smores', category: 'fidgets', fidgetType: 'spinner', name: 'S’mores', priceCents: 800, image: '/assets/photo-coming-soon.svg', imageKind: 'pending', type: 'Spinner', description: 'A s’mores-inspired fidget that spins.', detail: 'A s’mores-inspired 3D printed spinner. A real product photo is coming soon.' },
  { id: 'fortune-cookie', category: 'wiggles', name: 'Fortune Cookie Wiggle', priceCents: 500, image: '/assets/fortune-cookie-studio.jpg', type: 'Little Wiggle', description: 'A folded little friend with a big smile.', detail: 'This tiny fortune-cookie character brings its cheerful face and playful movement to any desk, shelf, or gift bag.', makerworld: 'https://makerworld.com/en/models/2832394-cute-fortune-cookie-wiggle-print-in-place-toy' },
  { id: 'lo-mein', category: 'wiggles', name: 'Lo Mein Wiggle', priceCents: 500, image: '/assets/lo-mein-studio.jpg', type: 'Little Wiggle', description: 'A happy takeout box topped with twisty noodles.', detail: 'Our Lo Mein Wiggle is full of noodle-shop personality, from the curled noodles to the sweet little face on the takeout box.', makerworld: 'https://makerworld.com/en/models/2832368-cute-lo-mein-wiggle-print-in-place-desk-toy' },
  { id: 'california-roll', category: 'wiggles', name: 'California Roll Wiggle', priceCents: 500, image: '/assets/california-roll-studio.jpg', type: 'Little Wiggle', description: 'A colorful sushi friend with rice-textured sides.', detail: 'This cheerful roll has a colorful top and a friendly face. It makes a cute companion for the rest of the sushi Wiggles.', makerworld: 'https://makerworld.com/en/models/2832307-cute-california-roll-wiggle-print-in-place-toy' },
  { id: 'salmon-nigiri', category: 'wiggles', name: 'Salmon Nigiri Wiggle', priceCents: 500, image: '/assets/salmon-nigiri-studio.jpg', type: 'Little Wiggle', description: 'A smiling rice-and-salmon desk buddy.', detail: 'A bright salmon-colored top and a tiny smiling rice base make this one a favorite in the Little Wiggles crew.', makerworld: 'https://makerworld.com/en/models/2832222-cute-salmon-nigiri-wiggle-print-in-place-toy' },
  { id: 'soy-sauce', category: 'wiggles', name: 'Soy Sauce Wiggle', priceCents: 500, image: '/assets/soy-sauce-studio.jpg', type: 'Little Wiggle', description: 'The adorable sidekick to every sushi Wiggle.', detail: 'A tiny bottle-shaped character with a bright cap and friendly face. It is ready to join your desk-side sushi party.', makerworld: 'https://makerworld.com/en/models/2832176-cute-soy-sauce-wiggle-print-in-place-desk-toy' },
  { id: 'egg-roll', category: 'wiggles', name: 'Egg Roll Wiggle', priceCents: 500, image: '/assets/egg-roll-studio.jpg', type: 'Little Wiggle', description: 'Golden, grinny, and ready to wiggle.', detail: 'The folded wrapper shape gives this cheerful egg roll plenty of character. A little bit of snack-inspired fun for your everyday space.', makerworld: 'https://makerworld.com/en/models/2832035-cute-egg-roll-wiggle-print-in-place-desk-toy' },
  { id: 'dumpling', category: 'wiggles', name: 'Dumpling Wiggle', priceCents: 500, image: '/assets/dumpling-studio.jpg', type: 'Little Wiggle', description: 'A crimped-edge cutie with a happy face.', detail: 'The fan-like dumpling folds and tiny smile make this Little Wiggle a sweet little desk companion.', makerworld: 'https://makerworld.com/en/models/2831942-cute-dumpling-wiggle-print-in-place-desk-toy' }
];

export const collections = {
  fidgets: { name: 'Fidgets', price: '$8 each', eyebrow: 'THE FIDGET COUNTER', title: 'Busy hands, happy hearts.', intro: 'Explore our magnet sliders and spinners. Every food-inspired fidget is a little different.' },
  wiggles: { name: 'Wiggles', price: '$5 each', eyebrow: 'MEET THE LITTLE WIGGLES', title: 'Tiny friends. Big smiles.', intro: 'The cutest desk companions in the bakery: happy little food characters ready to brighten your day.' }
};

export const shippingCents = 500;
export const freeShippingOverCents = 2500;
