export const catalog = [
  { id: 'chocolate-chip-cookie', category: 'fidgets', name: 'Chocolate Chip Cookie Spinner', priceCents: 800, image: '/assets/chocolate-chip-cookie-studio.jpg', type: 'Spinner', description: 'A classic cookie-shaped spinner with a smooth center hold.', detail: 'This bakery favorite puts a playful spin on a classic chocolate chip cookie. Hold the center and give the cookie a whirl for a satisfying little desk break.', makerworld: 'https://makerworld.com/en/models/2944943-chocolate-chip-cookie-fidget-spinner' },
  { id: 'black-white-cookie', category: 'fidgets', name: 'Black & White Cookie Spinner', priceCents: 800, image: '/assets/black-white-cookie-studio.jpg', type: 'Spinner', description: 'Two-tone cookie style with a satisfying spin.', detail: 'A bakery classic reimagined as a handheld fidget. The contrasting black-and-white face makes every spin fun to watch.', makerworld: 'https://makerworld.com/en/models/2944564-black-and-white-cookie-fidget-spinner' },
  { id: 'peanut-butter-cookie', category: 'fidgets', name: 'Peanut Butter Cookie Slider', priceCents: 800, image: '/assets/peanut-butter-cookie-studio.jpg', type: 'Magnetic slider', description: 'A layered peanut-butter-cookie look made to slide.', detail: 'Crisscross cookie texture on top, a layered shape underneath, and a compact magnetic sliding motion make this one easy to keep close at hand.', makerworld: 'https://makerworld.com/en/models/2944486-peanut-butter-cookie-fidget' },
  { id: 'chocolate-cupcake', category: 'fidgets', name: 'Chocolate Cupcake Spinner', priceCents: 800, image: '/assets/chocolate-cupcake-studio.jpg', type: 'Spinner', description: 'Chocolate-brown cupcake charm with a playful spin.', detail: 'The rich chocolate color and tiny icing detail give this spinner a sweet look. It is a small, sturdy 3D printed toy designed for busy hands.', makerworld: 'https://makerworld.com/en/models/2940355-chocolate-cupcake-fidget-spinner-toy' },
  { id: 'fortune-cookie', category: 'wiggles', name: 'Fortune Cookie Wiggle', priceCents: 500, image: '/assets/fortune-cookie-studio.jpg', type: 'Little Wiggle', description: 'A folded little friend with a big smile.', detail: 'This tiny fortune-cookie character brings its cheerful face and playful movement to any desk, shelf, or gift bag.', makerworld: 'https://makerworld.com/en/models/2832394-cute-fortune-cookie-wiggle-print-in-place-toy' },
  { id: 'lo-mein', category: 'wiggles', name: 'Lo Mein Wiggle', priceCents: 500, image: '/assets/lo-mein-studio.jpg', type: 'Little Wiggle', description: 'A happy takeout box topped with twisty noodles.', detail: 'Our Lo Mein Wiggle is full of noodle-shop personality, from the curled noodles to the sweet little face on the takeout box.', makerworld: 'https://makerworld.com/en/models/2832368-cute-lo-mein-wiggle-print-in-place-desk-toy' },
  { id: 'california-roll', category: 'wiggles', name: 'California Roll Wiggle', priceCents: 500, image: '/assets/california-roll-studio.jpg', type: 'Little Wiggle', description: 'A colorful sushi friend with rice-textured sides.', detail: 'This cheerful roll has a colorful top and a friendly face. It makes a cute companion for the rest of the sushi Wiggles.', makerworld: 'https://makerworld.com/en/models/2832307-cute-california-roll-wiggle-print-in-place-toy' },
  { id: 'salmon-nigiri', category: 'wiggles', name: 'Salmon Nigiri Wiggle', priceCents: 500, image: '/assets/salmon-nigiri-studio.jpg', type: 'Little Wiggle', description: 'A smiling rice-and-salmon desk buddy.', detail: 'A bright salmon-colored top and a tiny smiling rice base make this one a favorite in the Little Wiggles crew.', makerworld: 'https://makerworld.com/en/models/2832222-cute-salmon-nigiri-wiggle-print-in-place-toy' },
  { id: 'soy-sauce', category: 'wiggles', name: 'Soy Sauce Wiggle', priceCents: 500, image: '/assets/soy-sauce-studio.jpg', type: 'Little Wiggle', description: 'The adorable sidekick to every sushi Wiggle.', detail: 'A tiny bottle-shaped character with a bright cap and friendly face. It is ready to join your desk-side sushi party.', makerworld: 'https://makerworld.com/en/models/2832176-cute-soy-sauce-wiggle-print-in-place-desk-toy' },
  { id: 'egg-roll', category: 'wiggles', name: 'Egg Roll Wiggle', priceCents: 500, image: '/assets/egg-roll-studio.jpg', type: 'Little Wiggle', description: 'Golden, grinny, and ready to wiggle.', detail: 'The folded wrapper shape gives this cheerful egg roll plenty of character. A little bit of snack-inspired fun for your everyday space.', makerworld: 'https://makerworld.com/en/models/2832035-cute-egg-roll-wiggle-print-in-place-desk-toy' },
  { id: 'dumpling', category: 'wiggles', name: 'Dumpling Wiggle', priceCents: 500, image: '/assets/dumpling-studio.jpg', type: 'Little Wiggle', description: 'A crimped-edge cutie with a happy face.', detail: 'The fan-like dumpling folds and tiny smile make this Little Wiggle a sweet little desk companion.', makerworld: 'https://makerworld.com/en/models/2831942-cute-dumpling-wiggle-print-in-place-desk-toy' }
];

export const collections = {
  fidgets: { name: 'Fidgets', price: '$8 each', eyebrow: 'THE FIDGET COUNTER', title: 'Busy hands, happy hearts.', intro: 'Spin it, slide it, and find your favorite little moment of calm. Each food-inspired fidget has its own personality.' },
  wiggles: { name: 'Wiggles', price: '$5 each', eyebrow: 'MEET THE LITTLE WIGGLES', title: 'Tiny friends. Big smiles.', intro: 'The cutest desk companions in the bakery: happy little food characters ready to brighten your day.' }
};
